# -*- coding: utf-8 -*-
"""
Compute source data for Supplementary Figs. S8-S10 and Tables S2-S5.

This script is designed for the analysis output folder generated by the
same-condition motif-statistics pipeline. It uses:

  required:
    - motif_analysis_arrays.npz

  required for readout form-factor fits:
    - orthogonal_motif_coordinates_site_currents.csv
    - per_image_BAH_site_positions.csv

Outputs are written to:
    <analysis folder>/supplementary_source_data/

Main output groups:
  Fig. S8  - higher-order shell spectral content and sqrt(3)-peak detectability
  Fig. S9  - synthetic validation of reciprocal-space readout estimator
  Fig. S10 - observed/fitted complex Fourier coefficients and fit robustness
  Table S2 - synthetic validation metrics
  Table S3 - readout fit summary and robustness statistics
  Table S4 - current-floor correlations before/after readout correction
  Table S5 - component-level regression coefficients

"""

from __future__ import annotations

import argparse
import json
import math
import warnings
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

import numpy as np
import pandas as pd
from scipy import ndimage
from scipy.optimize import minimize
from scipy.stats import spearmanr, pearsonr

# =============================================================================
# USER SETTINGS
# =============================================================================

MAP_KEY = "aligned_norm"
OUTPUT_FOLDER_NAME = "supplementary_source_data"

# Reciprocal-shell definitions for the displayed 120-degree direct unit cell:
# q2(h,k) = h^2 + h*k + k^2.
FIRST_SHELL_HK = [(1, 0), (-1, 0), (0, 1), (0, -1), (1, -1), (-1, 1)]
SQRT3_SHELL_HK = [(-2, 1), (-1, -1), (-1, 2), (1, -2), (1, 1), (2, -1)]
TWOBY_SHELL_HK = [(2, 0), (-2, 0), (0, 2), (0, -2), (2, -2), (-2, 2)]
FIT_SHELL_HK = FIRST_SHELL_HK + SQRT3_SHELL_HK

SNR_THRESHOLD = 5.0
NOISE_Q2_MIN = 2
NOISE_Q2_MAX = 8
NOISE_EXCLUDED_Q2 = {0, 1, 3, 4}
NOISE_MAX_ABS_INDEX = 5

# Isotropic readout-width fitting: K(h,k)=exp[-beta*(q2-1)], so first shell has unit decay.
BETA_MIN = 0.0
BETA_MAX = 2.5
BETA_N_GRID = 501
BETA_CAP_TOL = 1e-6

# Synthetic validation settings
SYNTH_GRID_N = 64
SYNTH_WIDTH_VALUES = np.linspace(0.25, 1.80, 28)
SYNTH_CONTRAST_VALUES = np.linspace(0.0, 1.85, 34)  # c_beta at fixed c_AH
SYNTH_FIXED_C_AH = 1.00
SYNTH_FIXED_BETA = 0.95
SYNTH_ANISO_MAG_VALUES = np.linspace(0.0, 0.85, 18)
SYNTH_ANISO_ORIENTATION_DEG = 30.0
SYNTH_ANISO_BETA_EQUIV = 0.95
RANDOM_SEED = 20260626
ADD_SYNTH_NOISE = False
SYNTH_NOISE_SD = 0.0

# Robustness variants for Fig. S10e/Table S3 auxiliary checks
ROBUSTNESS_SNR_THRESHOLDS = [0.0, 5.0, 10.0]
BOOTSTRAP_N = 1000
BOOTSTRAP_SEED = 20260627

# Current-floor and motif columns from the main pipeline
FLOOR_COL_CANDIDATES = [
    "raw_current_floor_log10_abs_p05",
    "raw_current_floor_log10_abs",
    "CURRENT_FLOOR_PRIMARY_METRIC",
]
CONTRAST_COLUMNS = {
    "c_AH": "c_AH_norm",
    "c_B_signed": "c_beta_signed_norm",
    "abs_c_B": "abs_c_beta_norm",
    "theta_deg": "theta_beta_over_AH_deg_norm",
}

# For physical width conversion only; beta itself is the primary dimensionless readout descriptor.
GRAPHITE_LATTICE_A_NM = 0.246

# =============================================================================
# Basic utilities
# =============================================================================

def ensure_dir(p: Path) -> Path:
    p.mkdir(parents=True, exist_ok=True)
    return p


def safe_float(x) -> float:
    try:
        y = float(x)
        return y if np.isfinite(y) else np.nan
    except Exception:
        return np.nan


def robust_z(a: np.ndarray) -> np.ndarray:
    arr = np.asarray(a, dtype=float)
    med = np.nanmedian(arr)
    mad = np.nanmedian(np.abs(arr - med))
    scale = 1.4826 * mad
    if not np.isfinite(scale) or scale <= 1e-15:
        scale = np.nanstd(arr)
    if not np.isfinite(scale) or scale <= 1e-15:
        scale = 1.0
    return (arr - med) / scale


def zero_mean(a: np.ndarray) -> np.ndarray:
    arr = np.asarray(a, dtype=float)
    return arr - np.nanmean(arr)


def q2_120(h: int, k: int) -> int:
    """Squared reciprocal radius for the 120-degree direct-cell convention."""

    return int(h * h + h * k + k * k)


def hk_to_cartesian_G(h: int | float, k: int | float) -> Tuple[float, float]:
    """Cartesian reciprocal coordinates for the 120-degree direct cell."""
    h = float(h)
    k = float(k)
    return h, (2.0 * k + h) / math.sqrt(3.0)


def circular_axis_angle_diff_deg(a: float, b: float) -> float:
    """Absolute axis angle difference in degrees for a 180-degree-periodic principal axis."""
    d = ((float(a) - float(b) + 90.0) % 180.0) - 90.0
    return abs(d)


def spearman_safe(x, y) -> Tuple[float, float, int]:
    x = pd.to_numeric(pd.Series(x), errors="coerce").to_numpy(dtype=float)
    y = pd.to_numeric(pd.Series(y), errors="coerce").to_numpy(dtype=float)
    m = np.isfinite(x) & np.isfinite(y)
    if m.sum() < 4:
        return np.nan, np.nan, int(m.sum())
    r = spearmanr(x[m], y[m])
    return float(r.correlation), float(r.pvalue), int(m.sum())


def pearson_safe(x, y) -> Tuple[float, float, int]:
    x = pd.to_numeric(pd.Series(x), errors="coerce").to_numpy(dtype=float)
    y = pd.to_numeric(pd.Series(y), errors="coerce").to_numpy(dtype=float)
    m = np.isfinite(x) & np.isfinite(y)
    if m.sum() < 4:
        return np.nan, np.nan, int(m.sum())
    r = pearsonr(x[m], y[m])
    return float(r.statistic), float(r.pvalue), int(m.sum())


def bootstrap_spearman_ci(x, y, nboot: int = BOOTSTRAP_N, seed: int = BOOTSTRAP_SEED) -> Tuple[float, float, float, float, int]:
    x = pd.to_numeric(pd.Series(x), errors="coerce").to_numpy(dtype=float)
    y = pd.to_numeric(pd.Series(y), errors="coerce").to_numpy(dtype=float)
    m = np.isfinite(x) & np.isfinite(y)
    x = x[m]
    y = y[m]
    n = int(x.size)
    if n < 4:
        return np.nan, np.nan, np.nan, np.nan, n
    rho, pval, _ = spearman_safe(x, y)
    rng = np.random.default_rng(seed)
    idx = np.arange(n)
    boots = np.empty(nboot, dtype=float)
    for b in range(nboot):
        ii = rng.choice(idx, size=n, replace=True)
        boots[b], _, _ = spearman_safe(x[ii], y[ii])
    return rho, pval, float(np.nanpercentile(boots, 2.5)), float(np.nanpercentile(boots, 97.5)), n


def linear_regression_centered(x, y) -> Dict[str, float]:
    x = pd.to_numeric(pd.Series(x), errors="coerce").to_numpy(dtype=float)
    y = pd.to_numeric(pd.Series(y), errors="coerce").to_numpy(dtype=float)
    m = np.isfinite(x) & np.isfinite(y)
    if m.sum() < 4:
        return {"n": int(m.sum()), "slope": np.nan, "intercept": np.nan, "r2": np.nan,
                "x_mean": np.nan, "x_std": np.nan, "standardized_displacement": np.nan}
    xx = x[m]
    yy = y[m]
    X = np.column_stack([np.ones_like(xx), xx])
    coef, *_ = np.linalg.lstsq(X, yy, rcond=None)
    yhat = X @ coef
    ss_res = float(np.sum((yy - yhat) ** 2))
    ss_tot = float(np.sum((yy - np.mean(yy)) ** 2))
    r2 = 1.0 - ss_res / ss_tot if ss_tot > 0 else np.nan
    x_std = float(np.std(xx, ddof=1)) if xx.size > 1 else np.nan
    return {
        "n": int(xx.size),
        "intercept": float(coef[0]),
        "slope": float(coef[1]),
        "r2": float(r2),
        "x_mean": float(np.mean(xx)),
        "x_std": x_std,
        "standardized_displacement": float(coef[1] * x_std) if np.isfinite(x_std) else np.nan,
    }


def bootstrap_linear_regression_ci(x, y, nboot: int = BOOTSTRAP_N, seed: int = BOOTSTRAP_SEED) -> Dict[str, float]:
    x = pd.to_numeric(pd.Series(x), errors="coerce").to_numpy(dtype=float)
    y = pd.to_numeric(pd.Series(y), errors="coerce").to_numpy(dtype=float)
    m = np.isfinite(x) & np.isfinite(y)
    x = x[m]
    y = y[m]
    n = int(x.size)
    if n < 4:
        return {
            "slope_ci95_low": np.nan, "slope_ci95_high": np.nan,
            "standardized_displacement_ci95_low": np.nan, "standardized_displacement_ci95_high": np.nan,
            "r2_ci95_low": np.nan, "r2_ci95_high": np.nan,
        }
    rng = np.random.default_rng(seed)
    idx = np.arange(n)
    slopes = []
    disps = []
    r2s = []
    for _ in range(nboot):
        ii = rng.choice(idx, size=n, replace=True)
        d = linear_regression_centered(x[ii], y[ii])
        slopes.append(d["slope"])
        disps.append(d["standardized_displacement"])
        r2s.append(d["r2"])
    return {
        "slope_ci95_low": float(np.nanpercentile(slopes, 2.5)),
        "slope_ci95_high": float(np.nanpercentile(slopes, 97.5)),
        "standardized_displacement_ci95_low": float(np.nanpercentile(disps, 2.5)),
        "standardized_displacement_ci95_high": float(np.nanpercentile(disps, 97.5)),
        "r2_ci95_low": float(np.nanpercentile(r2s, 2.5)),
        "r2_ci95_high": float(np.nanpercentile(r2s, 97.5)),
    }

# =============================================================================
# Load inputs
# =============================================================================

def load_npz_maps(npz_path: Path, map_key: str) -> Tuple[np.ndarray, List[str], Dict[str, np.ndarray]]:
    if not npz_path.exists():
        raise FileNotFoundError(f"NPZ file not found: {npz_path}")
    data = np.load(npz_path, allow_pickle=True)
    keys = list(data.keys())
    if map_key not in keys:
        raise KeyError(f"MAP_KEY={map_key!r} not found in {npz_path}. Available keys: {keys}")
    maps = np.asarray(data[map_key], dtype=float)
    if maps.ndim != 3:
        raise ValueError(f"{map_key} must have shape (n_images, grid, grid), got {maps.shape}")
    if "names" in keys:
        names = [str(x) for x in data["names"].tolist()]
    else:
        names = [f"image_{i:04d}" for i in range(maps.shape[0])]
    arrays = {k: data[k] for k in keys}
    return maps, names, arrays


def load_coord_table(analysis_dir: Path, names: Sequence[str]) -> pd.DataFrame:
    path = analysis_dir / "orthogonal_motif_coordinates_site_currents.csv"
    if path.exists():
        df = pd.read_csv(path)
        if "name" not in df.columns:
            raise ValueError(f"{path} does not contain a 'name' column.")
        return df
    warnings.warn(f"Coordinate table not found: {path}. Some outputs will be missing.")
    return pd.DataFrame({"name": list(names), "short_name": list(names)})


def load_site_positions(analysis_dir: Path, coord_df: pd.DataFrame, names: Sequence[str]) -> Dict[str, Dict[str, Tuple[float, float]]]:
    site_path = analysis_dir / "per_image_BAH_site_positions.csv"
    positions: Dict[str, Dict[str, Tuple[float, float]]] = {}
    if site_path.exists():
        df = pd.read_csv(site_path)
        required = {"name", "site", "u", "v"}
        if not required.issubset(df.columns):
            raise ValueError(f"{site_path} must contain columns {required}")
        for nm, g in df.groupby("name"):
            d: Dict[str, Tuple[float, float]] = {}
            for _, r in g.iterrows():
                site = str(r["site"])
                if site in {"B", "A", "H"}:
                    d[site] = (float(r["u"]), float(r["v"]))
            if {"B", "A", "H"}.issubset(d):
                positions[str(nm)] = d
    elif {"B_u_used", "B_v_used", "A_u_used", "A_v_used", "H_u_used", "H_v_used"}.issubset(coord_df.columns):
        for _, r in coord_df.iterrows():
            nm = str(r["name"])
            positions[nm] = {
                "B": (float(r["B_u_used"]), float(r["B_v_used"])),
                "A": (float(r["A_u_used"]), float(r["A_v_used"])),
                "H": (float(r["H_u_used"]), float(r["H_v_used"])),
            }
    else:
        warnings.warn("No per-image B/A/H positions found. Readout form-factor fits require site positions.")
    missing = [nm for nm in names if nm not in positions]
    if missing:
        warnings.warn(f"Site positions missing for {len(missing)} images. These images will be skipped in readout fits.")
    return positions


def find_floor_col(df: pd.DataFrame) -> Optional[str]:
    for c in FLOOR_COL_CANDIDATES:
        if c in df.columns:
            return c
    # loose fallback
    for c in df.columns:
        if "floor" in c and "log10" in c and "abs" in c:
            return c
    return None

# =============================================================================
# Fourier coefficient helpers
# =============================================================================

def map_fft_coeffs(unit_map: np.ndarray, hks: Sequence[Tuple[int, int]]) -> np.ndarray:
    """Direct complex DFT coefficients at integer fractional-cell indices (h,k).

    The folded unit-cell map array convention is rows=v and columns=u.
    Coefficients are normalized by the number of pixels so amplitudes are stable
    when the grid size changes.
    """
    z = zero_mean(np.asarray(unit_map, dtype=float))
    n_v, n_u = z.shape
    u = np.arange(n_u, dtype=float) / float(n_u)
    v = np.arange(n_v, dtype=float) / float(n_v)
    U, V = np.meshgrid(u, v)
    coeffs = []
    for h, k in hks:
        phase = np.exp(-2j * np.pi * (float(h) * U + float(k) * V))
        coeffs.append(np.sum(z * phase) / float(n_u * n_v))
    return np.asarray(coeffs, dtype=np.complex128)


def coeff_table_for_map(unit_map: np.ndarray, name: str, hks: Sequence[Tuple[int, int]], shell: str) -> pd.DataFrame:
    c = map_fft_coeffs(unit_map, hks)
    rows = []
    for (h, k), val in zip(hks, c):
        gx, gy = hk_to_cartesian_G(h, k)
        rows.append({
            "name": name,
            "shell": shell,
            "h": int(h),
            "k": int(k),
            "q2_120": q2_120(int(h), int(k)),
            "Gx_cart": gx,
            "Gy_cart": gy,
            "coeff_real": float(np.real(val)),
            "coeff_imag": float(np.imag(val)),
            "amplitude": float(abs(val)),
            "power": float(abs(val) ** 2),
            "phase_rad": float(np.angle(val)),
        })
    return pd.DataFrame(rows)


def local_noise_hks() -> List[Tuple[int, int]]:
    out = []
    for h in range(-NOISE_MAX_ABS_INDEX, NOISE_MAX_ABS_INDEX + 1):
        for k in range(-NOISE_MAX_ABS_INDEX, NOISE_MAX_ABS_INDEX + 1):
            q2 = q2_120(h, k)
            if q2 < NOISE_Q2_MIN or q2 > NOISE_Q2_MAX:
                continue
            if q2 in NOISE_EXCLUDED_Q2:
                continue
            out.append((h, k))
    # deterministic unique order
    return sorted(set(out), key=lambda hk: (q2_120(*hk), hk[0], hk[1]))


def tiled_fft_xyz(unit_map: np.ndarray, tile_reps: int = 16, crop_hk: float = 5.5, smooth_sigma_px: float = 0.75) -> pd.DataFrame:
    """Raw-like FFT map from a tiled folded unit cell, as long-format xyz data.

    h/k are the reciprocal indices of the original unit cell. Tiling by tile_reps
    sharpens peaks and makes the sixfold pattern easier to plot.
    """
    z = zero_mean(np.asarray(unit_map, dtype=float))
    tiled = np.tile(z, (int(tile_reps), int(tile_reps)))
    F = np.fft.fftshift(np.fft.fft2(tiled)) / tiled.size
    power = np.abs(F) ** 2
    if smooth_sigma_px and smooth_sigma_px > 0:
        power_smooth = ndimage.gaussian_filter(power, sigma=float(smooth_sigma_px))
    else:
        power_smooth = power
    eps = max(float(np.nanmax(power)) * 1e-14, 1e-300)
    logp = np.log10(power + eps)
    logp_smooth = np.log10(power_smooth + eps)
    n = tiled.shape[0]
    freq = np.fft.fftshift(np.fft.fftfreq(n)) * (n / float(tile_reps))
    H, K = np.meshgrid(freq, freq)
    Gx = H
    Gy = (2.0 * K + H) / math.sqrt(3.0)
    mask = (np.abs(H) <= crop_hk) & (np.abs(K) <= crop_hk)
    return pd.DataFrame({
        "h": H[mask].ravel(),
        "k": K[mask].ravel(),
        "Gx_cart": Gx[mask].ravel(),
        "Gy_cart": Gy[mask].ravel(),
        "log10_power_raw": logp[mask].ravel(),
        "log10_power_smooth_for_plot": logp_smooth[mask].ravel(),
        "power_raw": power[mask].ravel(),
        "power_smooth_for_plot": power_smooth[mask].ravel(),
    })

# =============================================================================
# Readout form-factor fitting
# =============================================================================

def structure_factor_values(
    hks: Sequence[Tuple[int, int]],
    positions: Dict[str, Tuple[float, float]],
    intensities: Sequence[float],
) -> np.ndarray:
    IB, IA, IH = [float(x) for x in intensities]
    vals = []
    for h, k in hks:
        s = 0.0 + 0.0j
        for role, I in zip(("B", "A", "H"), (IB, IA, IH)):
            u, v = positions[role]
            s += I * np.exp(-2j * np.pi * (h * float(u) + k * float(v)))
        vals.append(s)
    return np.asarray(vals, dtype=np.complex128)


def design_matrix_isotropic(hks: Sequence[Tuple[int, int]], positions: Dict[str, Tuple[float, float]], beta: float) -> np.ndarray:
    D = []
    for h, k in hks:
        K_decay = math.exp(-float(beta) * (float(q2_120(h, k)) - 1.0))
        row = []
        for role in ("B", "A", "H"):
            u, v = positions[role]
            row.append(K_decay * np.exp(-2j * np.pi * (h * float(u) + k * float(v))))
        D.append(row)
    return np.asarray(D, dtype=np.complex128)


def solve_real_intensities_complex_lstsq(D: np.ndarray, y: np.ndarray, weights: Optional[np.ndarray] = None) -> Tuple[np.ndarray, float, float]:
    A = np.vstack([D.real, D.imag])
    b = np.concatenate([y.real, y.imag])
    if weights is not None:
        w = np.asarray(weights, dtype=float)
        ww = np.concatenate([w, w])
        A = A * ww[:, None]
        b = b * ww
    finite = np.isfinite(A).all(axis=1) & np.isfinite(b)
    if finite.sum() < 3:
        return np.full(3, np.nan), np.nan, np.nan
    sol, *_ = np.linalg.lstsq(A[finite], b[finite], rcond=None)
    yhat = D @ sol
    rss = float(np.nanmean(np.abs(y - yhat) ** 2))
    denom = float(np.nanmean(np.abs(y) ** 2))
    residual_fraction = rss / denom if denom > 0 else np.nan
    return sol.astype(float), rss, residual_fraction


@dataclass
class IsoFit:
    beta: float
    intensities: np.ndarray
    rss: float
    residual_fraction: float
    fitted: np.ndarray
    beta_railed_low: bool
    beta_railed_high: bool


def fit_isotropic_beta_from_coeffs(
    y: np.ndarray,
    hks_fit: Sequence[Tuple[int, int]],
    positions: Dict[str, Tuple[float, float]],
    weights: Optional[np.ndarray] = None,
    beta_min: float = BETA_MIN,
    beta_max: float = BETA_MAX,
    beta_n: int = BETA_N_GRID,
) -> IsoFit:
    grid = np.linspace(float(beta_min), float(beta_max), int(beta_n))
    best_beta = np.nan
    best_int = np.full(3, np.nan)
    best_rss = np.inf
    best_resid = np.nan
    best_fit = np.full(len(y), np.nan + 1j*np.nan, dtype=np.complex128)
    for beta in grid:
        D = design_matrix_isotropic(hks_fit, positions, float(beta))
        intensities, rss, resid = solve_real_intensities_complex_lstsq(D, y, weights=weights)
        if np.isfinite(rss) and rss < best_rss:
            best_beta = float(beta)
            best_int = intensities
            best_rss = float(rss)
            best_resid = float(resid)
            best_fit = D @ intensities
    return IsoFit(
        beta=best_beta,
        intensities=best_int,
        rss=best_rss,
        residual_fraction=best_resid,
        fitted=best_fit,
        beta_railed_low=bool(np.isfinite(best_beta) and abs(best_beta - beta_min) <= BETA_CAP_TOL),
        beta_railed_high=bool(np.isfinite(best_beta) and abs(best_beta - beta_max) <= BETA_CAP_TOL),
    )


def fit_isotropic_beta(unit_map: np.ndarray, positions: Dict[str, Tuple[float, float]], hks_fit: Sequence[Tuple[int, int]] = FIT_SHELL_HK, weights: Optional[np.ndarray] = None) -> IsoFit:
    y = map_fft_coeffs(unit_map, hks_fit)
    return fit_isotropic_beta_from_coeffs(y, hks_fit, positions, weights=weights)


def beta_to_gaussian_widths(beta: float) -> Dict[str, float]:
    if not np.isfinite(beta) or beta < 0:
        return {"sigma_frac_from_beta": np.nan, "fwhm_frac_from_beta": np.nan, "sigma_nm_from_beta": np.nan, "fwhm_nm_from_beta": np.nan}
    sigma_frac = math.sqrt(float(beta) / (2.0 * math.pi ** 2))
    fwhm_frac = 2.0 * math.sqrt(2.0 * math.log(2.0)) * sigma_frac
    return {
        "sigma_frac_from_beta": sigma_frac,
        "fwhm_frac_from_beta": fwhm_frac,
        "sigma_nm_from_beta": sigma_frac * GRAPHITE_LATTICE_A_NM,
        "fwhm_nm_from_beta": fwhm_frac * GRAPHITE_LATTICE_A_NM,
    }


def hk_to_g_vec(h: int | float, k: int | float) -> np.ndarray:
    gx, gy = hk_to_cartesian_G(h, k)
    return np.asarray([gx, gy], dtype=float)


def design_matrix_anisotropic(hks: Sequence[Tuple[int, int]], positions: Dict[str, Tuple[float, float]], Q: np.ndarray) -> np.ndarray:
    first_vals = []
    for h, k in FIRST_SHELL_HK:
        g = hk_to_g_vec(h, k)
        first_vals.append(float(g @ Q @ g))
    first_mean = float(np.mean(first_vals))
    D = []
    for h, k in hks:
        g = hk_to_g_vec(h, k)
        decay = float(g @ Q @ g) - first_mean
        K_decay = math.exp(-decay)
        row = []
        for role in ("B", "A", "H"):
            u, v = positions[role]
            row.append(K_decay * np.exp(-2j * np.pi * (h * float(u) + k * float(v))))
        D.append(row)
    return np.asarray(D, dtype=np.complex128)


def params_to_Q(params: Sequence[float]) -> np.ndarray:
    p0, p1, p2 = [float(x) for x in params]
    l00 = math.exp(np.clip(p0, -12, 6))
    l10 = p1
    l11 = math.exp(np.clip(p2, -12, 6))
    L = np.asarray([[l00, 0.0], [l10, l11]], dtype=float)
    return L @ L.T


def Q_to_outputs(Q: np.ndarray) -> Dict[str, float]:
    vals, vecs = np.linalg.eigh(Q)
    order = np.argsort(vals)
    vals = np.asarray(vals, dtype=float)[order]
    vecs = np.asarray(vecs, dtype=float)[:, order]
    lam_min, lam_max = float(vals[0]), float(vals[1])
    mean_decay = 0.5 * (lam_min + lam_max)
    eta = (lam_max - lam_min) / (lam_max + lam_min) if (lam_max + lam_min) > 0 else np.nan
    vmax_vec = vecs[:, 1]
    angle_deg = math.degrees(math.atan2(float(vmax_vec[1]), float(vmax_vec[0])))
    angle_deg = ((angle_deg + 90.0) % 180.0) - 90.0
    beta_equiv = (4.0 / 3.0) * mean_decay
    return {
        "anisotropic_Q_a": float(Q[0, 0]),
        "anisotropic_Q_b": float(2.0 * Q[0, 1]),
        "anisotropic_Q_c": float(Q[1, 1]),
        "anisotropic_lambda_min": lam_min,
        "anisotropic_lambda_max": lam_max,
        "anisotropic_mean_decay": mean_decay,
        "anisotropic_width_beta_equiv": beta_equiv,
        "anisotropic_magnitude_eta": eta,
        "anisotropic_orientation_deg": angle_deg,
    }


def isotropic_beta_to_initial_params(beta: float) -> np.ndarray:
    beta = max(float(beta), 1e-6) if np.isfinite(beta) else 0.5
    q = max(3.0 * beta / 4.0, 1e-9)
    L = np.linalg.cholesky(np.eye(2) * q)
    return np.asarray([math.log(L[0, 0]), L[1, 0], math.log(L[1, 1])], dtype=float)


def fit_anisotropic_from_coeffs(y: np.ndarray, hks_fit: Sequence[Tuple[int, int]], positions: Dict[str, Tuple[float, float]], beta_start: float) -> Dict[str, object]:
    def objective(params: np.ndarray) -> float:
        Q = params_to_Q(params)
        D = design_matrix_anisotropic(hks_fit, positions, Q)
        _, rss, _ = solve_real_intensities_complex_lstsq(D, y)
        if not np.isfinite(rss):
            return 1e99
        return float(rss)
    x0 = isotropic_beta_to_initial_params(beta_start)
    try:
        res = minimize(objective, x0, method="Nelder-Mead", options={"maxiter": 600, "xatol": 1e-8, "fatol": 1e-12})
        Q = params_to_Q(res.x)
        D = design_matrix_anisotropic(hks_fit, positions, Q)
        intensities, rss, resid = solve_real_intensities_complex_lstsq(D, y)
        fitted = D @ intensities
        out = Q_to_outputs(Q)
        out.update({
            "anisotropic_fit_success": bool(res.success),
            "anisotropic_fit_message": str(res.message),
            "anisotropic_rss": float(rss),
            "anisotropic_residual_fraction": float(resid),
            "anisotropic_fit_I_B": float(intensities[0]),
            "anisotropic_fit_I_A": float(intensities[1]),
            "anisotropic_fit_I_H": float(intensities[2]),
            "anisotropic_fitted_coefficients": fitted,
        })
        return out
    except Exception as exc:
        return {"anisotropic_fit_success": False, "anisotropic_fit_message": str(exc)}


def fit_anisotropic(unit_map: np.ndarray, positions: Dict[str, Tuple[float, float]], beta_start: float, hks_fit: Sequence[Tuple[int, int]] = FIT_SHELL_HK) -> Dict[str, object]:
    y = map_fft_coeffs(unit_map, hks_fit)
    return fit_anisotropic_from_coeffs(y, hks_fit, positions, beta_start)


def Q_from_beta_eta_phi(beta_equiv: float, eta: float, phi_deg: float) -> np.ndarray:
    """Build anisotropic Q matrix with a beta-equivalent mean decay and axis anisotropy eta."""
    mean_decay = 0.75 * float(beta_equiv)  # inverse of beta_equiv=(4/3)*mean_decay
    eta = float(eta)
    lam_max = mean_decay * (1.0 + eta)
    lam_min = mean_decay * (1.0 - eta)
    phi = math.radians(float(phi_deg))
    R = np.asarray([[math.cos(phi), -math.sin(phi)], [math.sin(phi), math.cos(phi)]], dtype=float)
    return R @ np.diag([lam_min, lam_max]) @ R.T

# =============================================================================
# Real-space texture descriptors for synthetic comparison
# =============================================================================

def synthetic_map_from_coeffs(hks: Sequence[Tuple[int, int]], coeffs: np.ndarray, n: int = SYNTH_GRID_N) -> np.ndarray:
    u = np.arange(n, dtype=float) / float(n)
    v = np.arange(n, dtype=float) / float(n)
    U, V = np.meshgrid(u, v)
    z = np.zeros((n, n), dtype=np.complex128)
    for (h, k), c in zip(hks, coeffs):
        z += c * np.exp(2j * np.pi * (float(h) * U + float(k) * V))
    return np.real(z)


def site_intensities_from_cAH_cbeta(c_AH: float, c_beta: float, common: float = 0.0) -> np.ndarray:
    # I = common*[1,1,1] + c_AH*(1,1,-2)/sqrt(6) + c_beta*(-1,1,0)/sqrt(2)
    return np.asarray([
        common + c_AH / math.sqrt(6.0) - c_beta / math.sqrt(2.0),
        common + c_AH / math.sqrt(6.0) + c_beta / math.sqrt(2.0),
        common - 2.0 * c_AH / math.sqrt(6.0),
    ], dtype=float)  # order: A, B, H


def convert_A_B_H_to_B_A_H(I_A_B_H: np.ndarray) -> np.ndarray:
    IA, IB, IH = [float(x) for x in I_A_B_H]
    return np.asarray([IB, IA, IH], dtype=float)


def synthetic_coeffs_isotropic(positions: Dict[str, Tuple[float, float]], intensities_BAH: Sequence[float], beta: float, hks: Sequence[Tuple[int,int]] = FIT_SHELL_HK) -> np.ndarray:
    S = structure_factor_values(hks, positions, intensities_BAH)
    K = np.asarray([math.exp(-float(beta) * (q2_120(h,k)-1.0)) for h,k in hks], dtype=float)
    return K * S


def synthetic_coeffs_anisotropic(positions: Dict[str, Tuple[float, float]], intensities_BAH: Sequence[float], Q: np.ndarray, hks: Sequence[Tuple[int,int]] = FIT_SHELL_HK) -> np.ndarray:
    D = design_matrix_anisotropic(hks, positions, Q)
    return D @ np.asarray(intensities_BAH, dtype=float)


def real_space_texture_descriptors(unit_map: np.ndarray) -> Dict[str, float]:
    z = robust_z(unit_map)
    z = zero_mean(z)
    n = z.shape[0]
    yy, xx = np.indices(z.shape)
    coords = (np.arange(n) + 0.5) / n
    U, V = np.meshgrid(coords, coords)
    weights = np.abs(z)
    sw = float(np.sum(weights))
    if sw <= 0:
        sw = 1.0
    uc = float(np.sum(U * weights) / sw)
    vc = float(np.sum(V * weights) / sw)
    du = ((U - uc + 0.5) % 1.0) - 0.5
    dv = ((V - vc + 0.5) % 1.0) - 0.5
    # second moment in square and graphite oblique metrics
    sigma_u = math.sqrt(max(0.0, float(np.sum(weights * du**2) / sw)))
    sigma_v = math.sqrt(max(0.0, float(np.sum(weights * dv**2) / sw)))
    sigma_hex = math.sqrt(max(0.0, float(np.sum(weights * (du**2 + dv**2 - du*dv)) / sw)))

    # autocorrelation central second moment
    F = np.fft.fft2(z)
    ac = np.fft.fftshift(np.real(np.fft.ifft2(np.abs(F)**2)))
    ac = np.maximum(ac - np.nanmin(ac), 0)
    sw_ac = float(np.sum(ac))
    cy, cx = np.array(ac.shape) // 2
    y = (np.arange(n) - cy) / n
    x = (np.arange(n) - cx) / n
    X, Y = np.meshgrid(x, y)
    if sw_ac <= 0:
        ac_sigma_x = ac_sigma_y = ac_sigma_r = np.nan
    else:
        ac_sigma_x = math.sqrt(max(0.0, float(np.sum(ac * X**2) / sw_ac)))
        ac_sigma_y = math.sqrt(max(0.0, float(np.sum(ac * Y**2) / sw_ac)))
        ac_sigma_r = math.sqrt(max(0.0, float(np.sum(ac * (X**2 + Y**2)) / sw_ac)))

    low = ndimage.gaussian_filter(z, sigma=max(1.0, n/12.0))
    hp = z - low
    lap = ndimage.laplace(z)
    gy, gx = np.gradient(z)
    return {
        "second_moment_sigma_u": sigma_u,
        "second_moment_sigma_v": sigma_v,
        "second_moment_sigma_hex": sigma_hex,
        "autocorr_sigma_x": ac_sigma_x,
        "autocorr_sigma_y": ac_sigma_y,
        "autocorr_sigma_r": ac_sigma_r,
        "highpass_energy_fraction": float(np.mean(hp**2) / (np.mean(z**2) + 1e-30)),
        "laplacian_energy": float(np.mean(lap**2)),
        "gradient_energy": float(np.mean(gx**2 + gy**2)),
        "peak_to_peak": float(np.nanmax(z) - np.nanmin(z)),
    }

# =============================================================================
# Fig. S8 data
# =============================================================================

def shell_marker_table() -> pd.DataFrame:
    rows = []
    for shell, hks in [("first", FIRST_SHELL_HK), ("sqrt3", SQRT3_SHELL_HK), ("2x", TWOBY_SHELL_HK)]:
        for h, k in hks:
            gx, gy = hk_to_cartesian_G(h, k)
            rows.append({"shell": shell, "h": h, "k": k, "q2_120": q2_120(h,k), "Gx_cart": gx, "Gy_cart": gy})
    return pd.DataFrame(rows)


def compute_S8(maps: np.ndarray, names: Sequence[str], out_dir: Path) -> pd.DataFrame:
    s8_dir = ensure_dir(out_dir / "Fig_S8_peak_detectability")
    shell_marker_table().to_csv(s8_dir / "S8a_shell_marker_points_for_overlay.csv", index=False, encoding="utf-8-sig")

    # Ensemble mean shell content
    mean_map = np.nanmean(maps, axis=0)
    coeff_rows = []
    for shell, hks in [("first", FIRST_SHELL_HK), ("sqrt3", SQRT3_SHELL_HK), ("2x", TWOBY_SHELL_HK)]:
        coeff_rows.append(coeff_table_for_map(mean_map, "ensemble_mean", hks, shell))
    ens_coeff_long = pd.concat(coeff_rows, ignore_index=True)
    ens_coeff_long.to_csv(s8_dir / "S8b_ensemble_mean_exact_shell_coefficients_long.csv", index=False, encoding="utf-8-sig")
    first_power = ens_coeff_long.loc[ens_coeff_long["shell"] == "first", "power"].mean()
    first_amp = ens_coeff_long.loc[ens_coeff_long["shell"] == "first", "amplitude"].mean()
    ens_summary_rows = []
    for shell in ["first", "sqrt3", "2x"]:
        sub = ens_coeff_long[ens_coeff_long["shell"] == shell]
        p = float(sub["power"].mean())
        a = float(sub["amplitude"].mean())
        ens_summary_rows.append({
            "shell": shell,
            "mean_amplitude": a,
            "mean_power": p,
            "amplitude_ratio_to_first": a / first_amp if first_amp > 0 else np.nan,
            "power_ratio_to_first": p / first_power if first_power > 0 else np.nan,
            "log10_mean_power": math.log10(max(p, 1e-300)),
        })
    ens_summary = pd.DataFrame(ens_summary_rows)
    ens_summary.to_csv(s8_dir / "S8b_ensemble_mean_shell_power_summary.csv", index=False, encoding="utf-8-sig")

    # Per-image SNR and shell amplitudes
    noise_hks = local_noise_hks()
    rows = []
    coeffs_all = []
    for i, (nm, m) in enumerate(zip(names, maps)):
        c_first = map_fft_coeffs(m, FIRST_SHELL_HK)
        c_sqrt3 = map_fft_coeffs(m, SQRT3_SHELL_HK)
        c_2x = map_fft_coeffs(m, TWOBY_SHELL_HK)
        c_noise = map_fft_coeffs(m, noise_hks)
        first_amp = float(np.nanmean(np.abs(c_first)))
        sqrt3_amp = float(np.nanmean(np.abs(c_sqrt3)))
        twox_amp = float(np.nanmean(np.abs(c_2x)))
        noise_amp_median = float(np.nanmedian(np.abs(c_noise))) if len(c_noise) else np.nan
        noise_amp_mean = float(np.nanmean(np.abs(c_noise))) if len(c_noise) else np.nan
        noise_power_median = float(np.nanmedian(np.abs(c_noise)**2)) if len(c_noise) else np.nan
        snr = sqrt3_amp / noise_amp_median if noise_amp_median > 0 else np.nan
        snr_2x = twox_amp / noise_amp_median if noise_amp_median > 0 else np.nan
        rows.append({
            "array_index": i,
            "name": nm,
            "first_amp_mean": first_amp,
            "sqrt3_amp_mean": sqrt3_amp,
            "twox_amp_mean": twox_amp,
            "sqrt3_amp_ratio_to_first": sqrt3_amp / first_amp if first_amp > 0 else np.nan,
            "twox_amp_ratio_to_first": twox_amp / first_amp if first_amp > 0 else np.nan,
            "sqrt3_power_ratio_to_first": (sqrt3_amp**2)/(first_amp**2) if first_amp > 0 else np.nan,
            "twox_power_ratio_to_first": (twox_amp**2)/(first_amp**2) if first_amp > 0 else np.nan,
            "local_noise_amp_median": noise_amp_median,
            "local_noise_amp_mean": noise_amp_mean,
            "local_noise_power_median": noise_power_median,
            "sqrt3_amp_snr": snr,
            "twox_amp_snr": snr_2x,
            "sqrt3_resolved": bool(np.isfinite(snr) and snr >= SNR_THRESHOLD),
            "twox_resolved": bool(np.isfinite(snr_2x) and snr_2x >= SNR_THRESHOLD),
        })
        # Long coefficient table for exact shell markers if needed
        for shell, hks, c in [("first", FIRST_SHELL_HK, c_first), ("sqrt3", SQRT3_SHELL_HK, c_sqrt3), ("2x", TWOBY_SHELL_HK, c_2x)]:
            for (h,k), val in zip(hks, c):
                gx, gy = hk_to_cartesian_G(h,k)
                coeffs_all.append({
                    "array_index": i, "name": nm, "shell": shell, "h": h, "k": k,
                    "q2_120": q2_120(h,k), "Gx_cart": gx, "Gy_cart": gy,
                    "coeff_real": float(np.real(val)), "coeff_imag": float(np.imag(val)),
                    "amplitude": float(abs(val)), "power": float(abs(val)**2), "phase_rad": float(np.angle(val)),
                })
    snr_df = pd.DataFrame(rows)
    snr_df.to_csv(s8_dir / "S8c_per_image_sqrt3_peak_snr.csv", index=False, encoding="utf-8-sig")
    pd.DataFrame(coeffs_all).to_csv(s8_dir / "S8_per_image_exact_shell_coefficients_long.csv", index=False, encoding="utf-8-sig")

    summary = pd.DataFrame([{
        "n_images": int(len(snr_df)),
        "snr_threshold": float(SNR_THRESHOLD),
        "sqrt3_resolved_count": int(snr_df["sqrt3_resolved"].sum()),
        "sqrt3_resolved_fraction": float(snr_df["sqrt3_resolved"].mean()),
        "sqrt3_snr_median": float(snr_df["sqrt3_amp_snr"].median()),
        "sqrt3_snr_p05": float(snr_df["sqrt3_amp_snr"].quantile(0.05)),
        "sqrt3_snr_p95": float(snr_df["sqrt3_amp_snr"].quantile(0.95)),
        "twox_snr_median": float(snr_df["twox_amp_snr"].median()),
        "twox_resolved_fraction": float(snr_df["twox_resolved"].mean()),
        "sqrt3_power_ratio_to_first_median": float(snr_df["sqrt3_power_ratio_to_first"].median()),
        "twox_power_ratio_to_first_median": float(snr_df["twox_power_ratio_to_first"].median()),
    }])
    summary.to_csv(s8_dir / "S8_peak_detectability_summary.csv", index=False, encoding="utf-8-sig")

    # Representative FFT maps for high, median, and near-threshold sqrt3 SNR.
    snr_vals = pd.to_numeric(snr_df["sqrt3_amp_snr"], errors="coerce")
    finite = snr_vals[np.isfinite(snr_vals)]
    rep_rows = []
    if len(finite):
        choices = {
            "high_snr": int(snr_vals.idxmax()),
            "median_snr": int((snr_vals - finite.median()).abs().idxmin()),
            "near_threshold_snr": int((snr_vals - SNR_THRESHOLD).abs().idxmin()),
        }
        for label, idx in choices.items():
            r = snr_df.loc[idx].to_dict()
            rep_rows.append({"representative_type": label, **r})
            xyz = tiled_fft_xyz(maps[int(r["array_index"])], tile_reps=16, crop_hk=5.5)
            xyz.to_csv(s8_dir / f"S8d_fft_map_{label}_xyz.csv", index=False, encoding="utf-8-sig")
    pd.DataFrame(rep_rows).to_csv(s8_dir / "S8d_representative_fft_selection.csv", index=False, encoding="utf-8-sig")
    return snr_df

# =============================================================================
# Real data readout fits for Fig. S10 / Tables S3-S5
# =============================================================================

def compute_real_readout_fits(maps: np.ndarray, names: Sequence[str], coord_df: pd.DataFrame, positions_by_name: Dict[str, Dict[str, Tuple[float,float]]], s8_snr_df: pd.DataFrame, out_dir: Path) -> Tuple[pd.DataFrame, pd.DataFrame]:
    fit_dir = ensure_dir(out_dir / "readout_form_factor_fits")
    coord_by_name = coord_df.set_index("name", drop=False) if "name" in coord_df.columns else pd.DataFrame()
    snr_by_name = s8_snr_df.set_index("name", drop=False) if not s8_snr_df.empty else pd.DataFrame()
    rows = []
    coeff_rows = []
    for i, (nm, unit_map) in enumerate(zip(names, maps)):
        if nm not in positions_by_name:
            continue
        pos = positions_by_name[nm]
        y = map_fft_coeffs(unit_map, FIT_SHELL_HK)
        iso = fit_isotropic_beta_from_coeffs(y, FIT_SHELL_HK, pos)
        aniso = fit_anisotropic_from_coeffs(y, FIT_SHELL_HK, pos, iso.beta)
        row = {
            "array_index": i,
            "name": nm,
            "beta_iso": float(iso.beta),
            "readout_width_beta": float(iso.beta),
            "beta_grid_railed_low": bool(iso.beta_railed_low),
            "beta_grid_railed_high": bool(iso.beta_railed_high),
            "isotropic_rss": float(iso.rss),
            "isotropic_residual_fraction": float(iso.residual_fraction),
            "isotropic_fit_I_B": float(iso.intensities[0]),
            "isotropic_fit_I_A": float(iso.intensities[1]),
            "isotropic_fit_I_H": float(iso.intensities[2]),
        }
        row.update(beta_to_gaussian_widths(iso.beta))
        # Shell ratios using fitted intensities
        c1 = map_fft_coeffs(unit_map, FIRST_SHELL_HK)
        c3 = map_fft_coeffs(unit_map, SQRT3_SHELL_HK)
        a1 = float(np.mean(np.abs(c1)))
        a3 = float(np.mean(np.abs(c3)))
        s1 = structure_factor_values(FIRST_SHELL_HK, pos, iso.intensities)
        s3 = structure_factor_values(SQRT3_SHELL_HK, pos, iso.intensities)
        sratio = float(np.mean(np.abs(s3)) / np.mean(np.abs(s1))) if np.mean(np.abs(s1)) > 0 else np.nan
        measured_ratio = a3/a1 if a1 > 0 else np.nan
        form_ratio = measured_ratio/sratio if np.isfinite(sratio) and sratio > 0 else np.nan
        row.update({
            "amp_ratio_sqrt3_over_first_measured": measured_ratio,
            "structure_ratio_sqrt3_over_first": sratio,
            "form_factor_ratio_sqrt3_over_first": form_ratio,
            "beta_shellratio_structure_corrected": -0.5*math.log(form_ratio) if form_ratio and form_ratio > 0 else np.nan,
        })
        # Anisotropic outputs
        for k, v in aniso.items():
            if k == "anisotropic_fitted_coefficients":
                continue
            if isinstance(v, (bool, str)):
                row[k] = v
            else:
                try:
                    row[k] = float(v)
                except Exception:
                    row[k] = v
        if nm in coord_by_name.index:
            c = coord_by_name.loc[nm]
            if isinstance(c, pd.DataFrame):
                c = c.iloc[0]
            for col in ["short_name", "c_AH_norm", "c_beta_signed_norm", "abs_c_beta_norm", "R_orthogonal_norm", "theta_beta_over_AH_deg_norm", "raw_current_floor_log10_abs_p05", "raw_current_floor_abs_p05"]:
                if col in c.index:
                    row[col] = c[col]
        if nm in snr_by_name.index:
            s = snr_by_name.loc[nm]
            if isinstance(s, pd.DataFrame):
                s = s.iloc[0]
            for col in ["sqrt3_amp_snr", "twox_amp_snr", "sqrt3_resolved"]:
                if col in s.index:
                    row[col] = s[col]
        rows.append(row)
        fitted_aniso = aniso.get("anisotropic_fitted_coefficients", np.full(len(FIT_SHELL_HK), np.nan+1j*np.nan))
        for shell, hks in [("first", FIRST_SHELL_HK), ("sqrt3", SQRT3_SHELL_HK)]:
            for (h,k) in hks:
                idx = FIT_SHELL_HK.index((h,k))
                obs = y[idx]
                iso_pred = iso.fitted[idx]
                ani_pred = fitted_aniso[idx] if len(fitted_aniso) > idx else np.nan + 1j*np.nan
                gx, gy = hk_to_cartesian_G(h,k)
                coeff_rows.append({
                    "array_index": i, "name": nm, "shell": shell, "h": h, "k": k, "q2_120": q2_120(h,k),
                    "Gx_cart": gx, "Gy_cart": gy,
                    "observed_real": float(obs.real), "observed_imag": float(obs.imag),
                    "observed_amplitude": float(abs(obs)), "observed_phase_rad": float(np.angle(obs)),
                    "isotropic_fit_real": float(np.real(iso_pred)), "isotropic_fit_imag": float(np.imag(iso_pred)),
                    "isotropic_fit_amplitude": float(abs(iso_pred)), "isotropic_residual_amplitude": float(abs(obs-iso_pred)),
                    "anisotropic_fit_real": float(np.real(ani_pred)), "anisotropic_fit_imag": float(np.imag(ani_pred)),
                    "anisotropic_fit_amplitude": float(abs(ani_pred)), "anisotropic_residual_amplitude": float(abs(obs-ani_pred)),
                })
    fit_df = pd.DataFrame(rows)
    coeff_df = pd.DataFrame(coeff_rows)
    if not fit_df.empty:
        # cap-excluded continuous subset flag
        fit_df["fit_included_continuous"] = (~fit_df["beta_grid_railed_high"].astype(bool)) & np.isfinite(pd.to_numeric(fit_df["beta_iso"], errors="coerce"))
        fit_df.to_csv(fit_dir / "readout_fit_per_image.csv", index=False, encoding="utf-8-sig")
    if not coeff_df.empty:
        coeff_df.to_csv(fit_dir / "observed_vs_fitted_complex_coefficients_all_images.csv", index=False, encoding="utf-8-sig")
    return fit_df, coeff_df

# =============================================================================
# Synthetic validation Fig. S9 / Table S2
# =============================================================================

def representative_site_positions(positions_by_name: Dict[str, Dict[str, Tuple[float,float]]]) -> Dict[str, Tuple[float,float]]:
    if not positions_by_name:
        # Fallback to a simple diagonal default.
        return {"B": (0.0, 0.0), "A": (2.0/3.0, 2.0/3.0), "H": (1.0/3.0, 1.0/3.0)}
    roles = {"B": [], "A": [], "H": []}
    for d in positions_by_name.values():
        for r in roles:
            if r in d:
                roles[r].append(d[r])
    out = {}
    for r, vals in roles.items():
        if not vals:
            continue
        arr = np.asarray(vals, dtype=float)
        # circular mean in unit interval
        u_angle = np.exp(2j*np.pi*arr[:,0])
        v_angle = np.exp(2j*np.pi*arr[:,1])
        u = (np.angle(np.mean(u_angle))/(2*np.pi)) % 1.0
        v = (np.angle(np.mean(v_angle))/(2*np.pi)) % 1.0
        out[r] = (float(u), float(v))
    if not {"B","A","H"}.issubset(out):
        return {"B": (0.0, 0.0), "A": (2.0/3.0, 2.0/3.0), "H": (1.0/3.0, 1.0/3.0)}
    return out


def compute_synthetic_validation(positions_by_name: Dict[str, Dict[str, Tuple[float,float]]], out_dir: Path) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    s9_dir = ensure_dir(out_dir / "Fig_S9_synthetic_validation")
    pos = representative_site_positions(positions_by_name)
    pd.DataFrame([{"site": k, "u": v[0], "v": v[1]} for k, v in pos.items()]).to_csv(
        s9_dir / "S9a_representative_synthetic_site_positions.csv", index=False, encoding="utf-8-sig"
    )
    rng = np.random.default_rng(RANDOM_SEED)
    # Width sensitivity sweep at fixed contrast character.
    fixed_intensities = convert_A_B_H_to_B_A_H(site_intensities_from_cAH_cbeta(SYNTH_FIXED_C_AH, 0.90))
    width_rows = []
    for beta in SYNTH_WIDTH_VALUES:
        coeff = synthetic_coeffs_isotropic(pos, fixed_intensities, beta)
        if ADD_SYNTH_NOISE and SYNTH_NOISE_SD > 0:
            coeff = coeff + (rng.normal(scale=SYNTH_NOISE_SD, size=coeff.shape) + 1j*rng.normal(scale=SYNTH_NOISE_SD, size=coeff.shape))
        m = synthetic_map_from_coeffs(FIT_SHELL_HK, coeff, n=SYNTH_GRID_N)
        iso = fit_isotropic_beta(m, pos)
        aniso = fit_anisotropic(m, pos, iso.beta)
        desc = real_space_texture_descriptors(m)
        row = {
            "sweep": "width_sensitivity",
            "imposed_beta": float(beta),
            "imposed_c_AH": SYNTH_FIXED_C_AH,
            "imposed_c_beta": 0.90,
            "fit_beta_iso": iso.beta,
            "fit_residual_fraction": iso.residual_fraction,
            "fit_I_B": iso.intensities[0], "fit_I_A": iso.intensities[1], "fit_I_H": iso.intensities[2],
            "anisotropic_width_beta_equiv": aniso.get("anisotropic_width_beta_equiv", np.nan),
            "anisotropic_magnitude_eta": aniso.get("anisotropic_magnitude_eta", np.nan),
            **desc,
        }
        width_rows.append(row)
    width_df = pd.DataFrame(width_rows)
    width_df.to_csv(s9_dir / "S9b_synthetic_width_sensitivity_sweep.csv", index=False, encoding="utf-8-sig")

    # Contrast specificity sweep at fixed readout.
    contrast_rows = []
    for c_beta in SYNTH_CONTRAST_VALUES:
        ints = convert_A_B_H_to_B_A_H(site_intensities_from_cAH_cbeta(SYNTH_FIXED_C_AH, float(c_beta)))
        coeff = synthetic_coeffs_isotropic(pos, ints, SYNTH_FIXED_BETA)
        if ADD_SYNTH_NOISE and SYNTH_NOISE_SD > 0:
            coeff = coeff + (rng.normal(scale=SYNTH_NOISE_SD, size=coeff.shape) + 1j*rng.normal(scale=SYNTH_NOISE_SD, size=coeff.shape))
        m = synthetic_map_from_coeffs(FIT_SHELL_HK, coeff, n=SYNTH_GRID_N)
        iso = fit_isotropic_beta(m, pos)
        aniso = fit_anisotropic(m, pos, iso.beta)
        desc = real_space_texture_descriptors(m)
        contrast_rows.append({
            "sweep": "contrast_specificity",
            "imposed_beta": SYNTH_FIXED_BETA,
            "imposed_c_AH": SYNTH_FIXED_C_AH,
            "imposed_c_beta": float(c_beta),
            "fit_beta_iso": iso.beta,
            "fit_residual_fraction": iso.residual_fraction,
            "fit_I_B": iso.intensities[0], "fit_I_A": iso.intensities[1], "fit_I_H": iso.intensities[2],
            "anisotropic_width_beta_equiv": aniso.get("anisotropic_width_beta_equiv", np.nan),
            "anisotropic_magnitude_eta": aniso.get("anisotropic_magnitude_eta", np.nan),
            **desc,
        })
    contrast_df = pd.DataFrame(contrast_rows)
    contrast_df.to_csv(s9_dir / "S9c_synthetic_contrast_specificity_sweep.csv", index=False, encoding="utf-8-sig")

    # Anisotropy validation sweep.
    aniso_rows = []
    for eta in SYNTH_ANISO_MAG_VALUES:
        Q = Q_from_beta_eta_phi(SYNTH_ANISO_BETA_EQUIV, float(eta), SYNTH_ANISO_ORIENTATION_DEG)
        coeff = synthetic_coeffs_anisotropic(pos, fixed_intensities, Q)
        m = synthetic_map_from_coeffs(FIT_SHELL_HK, coeff, n=SYNTH_GRID_N)
        iso = fit_isotropic_beta(m, pos)
        aniso = fit_anisotropic(m, pos, iso.beta)
        aniso_rows.append({
            "sweep": "anisotropy_validation",
            "imposed_beta_equiv": SYNTH_ANISO_BETA_EQUIV,
            "imposed_eta": float(eta),
            "imposed_orientation_deg": SYNTH_ANISO_ORIENTATION_DEG,
            "fit_beta_iso": iso.beta,
            "fit_anisotropic_width_beta_equiv": aniso.get("anisotropic_width_beta_equiv", np.nan),
            "fit_eta": aniso.get("anisotropic_magnitude_eta", np.nan),
            "fit_orientation_deg": aniso.get("anisotropic_orientation_deg", np.nan),
            "orientation_abs_error_deg": circular_axis_angle_diff_deg(aniso.get("anisotropic_orientation_deg", np.nan), SYNTH_ANISO_ORIENTATION_DEG),
            "anisotropic_residual_fraction": aniso.get("anisotropic_residual_fraction", np.nan),
        })
    aniso_df = pd.DataFrame(aniso_rows)
    aniso_df.to_csv(s9_dir / "S9d_synthetic_anisotropy_validation.csv", index=False, encoding="utf-8-sig")

    # Table S2 metrics.
    descriptor_cols = [
        "fit_beta_iso", "anisotropic_width_beta_equiv", "anisotropic_magnitude_eta",
        "second_moment_sigma_u", "second_moment_sigma_v", "second_moment_sigma_hex",
        "autocorr_sigma_x", "autocorr_sigma_y", "autocorr_sigma_r",
        "highpass_energy_fraction", "laplacian_energy", "gradient_energy", "peak_to_peak",
    ]
    rows = []
    for desc in descriptor_cols:
        if desc not in width_df.columns and desc not in contrast_df.columns:
            continue
        rho_width, p_width, n_width = spearman_safe(width_df.get("imposed_beta", []), width_df.get(desc, []))
        rho_leak, p_leak, n_leak = spearman_safe(contrast_df.get("imposed_c_beta", []), contrast_df.get(desc, []))
        rows.append({
            "estimator": desc,
            "width_sensitivity_spearman_rho": rho_width,
            "width_sensitivity_p": p_width,
            "width_sensitivity_n": n_width,
            "contrast_leakage_spearman_rho_vs_c_beta": rho_leak,
            "contrast_leakage_abs_rho": abs(rho_leak) if np.isfinite(rho_leak) else np.nan,
            "contrast_leakage_p": p_leak,
            "contrast_leakage_n": n_leak,
            "anisotropy_sensitivity_spearman_rho": np.nan,
            "orientation_error_median_deg": np.nan,
            "validation_pass": bool(np.isfinite(rho_width) and abs(rho_width) >= 0.90 and (not np.isfinite(rho_leak) or abs(rho_leak) <= 0.10)),
        })
    # Add anisotropic specific metrics.
    rho_eta, p_eta, n_eta = spearman_safe(aniso_df["imposed_eta"], aniso_df["fit_eta"])
    ori_med = float(aniso_df["orientation_abs_error_deg"].median())
    rows.append({
        "estimator": "anisotropic_form_factor_eta_phi",
        "width_sensitivity_spearman_rho": np.nan,
        "width_sensitivity_p": np.nan,
        "width_sensitivity_n": len(aniso_df),
        "contrast_leakage_spearman_rho_vs_c_beta": np.nan,
        "contrast_leakage_abs_rho": np.nan,
        "contrast_leakage_p": np.nan,
        "contrast_leakage_n": len(contrast_df),
        "anisotropy_sensitivity_spearman_rho": rho_eta,
        "anisotropy_sensitivity_p": p_eta,
        "anisotropy_sensitivity_n": n_eta,
        "orientation_error_median_deg": ori_med,
        "validation_pass": bool(np.isfinite(rho_eta) and abs(rho_eta) >= 0.90 and ori_med <= 5.0),
    })
    table_s2 = pd.DataFrame(rows)
    table_s2.to_csv(s9_dir / "Table_S2_synthetic_validation_metrics.csv", index=False, encoding="utf-8-sig")
    # A compact 2-axis summary for plotting panel S9e.
    plot_rows = table_s2.copy()
    plot_rows["x_width_sensitivity_abs_rho"] = plot_rows["width_sensitivity_spearman_rho"].abs()
    plot_rows["y_contrast_leakage_abs_rho"] = plot_rows["contrast_leakage_abs_rho"]
    plot_rows.to_csv(s9_dir / "S9e_two_axis_validation_summary_for_plot.csv", index=False, encoding="utf-8-sig")
    return width_df, contrast_df, aniso_df

# =============================================================================
# Fig. S10, Table S3-S5 data
# =============================================================================

def add_floor_and_coord_columns(fit_df: pd.DataFrame, coord_df: pd.DataFrame) -> pd.DataFrame:
    if fit_df.empty or coord_df.empty:
        return fit_df
    keep = ["name"] + [c for c in coord_df.columns if c in set(CONTRAST_COLUMNS.values()) or "floor" in c or c == "short_name"]
    keep = list(dict.fromkeys(keep))
    extra = coord_df[keep].copy()
    out = fit_df.copy()
    missing_cols = [c for c in extra.columns if c != "name" and c not in out.columns]
    if missing_cols:
        out = out.merge(extra[["name"] + missing_cols], on="name", how="left")
    return out


def compute_table_S3_and_S10(fit_df: pd.DataFrame, coeff_df: pd.DataFrame, out_dir: Path) -> None:
    s10_dir = ensure_dir(out_dir / "Fig_S10_readout_fit_robustness")
    if fit_df.empty:
        warnings.warn("No readout fit data available; skipping Fig S10/Table S3 outputs.")
        return
    fit_df.to_csv(s10_dir / "S10_all_readout_fit_per_image.csv", index=False, encoding="utf-8-sig")
    if not coeff_df.empty:
        coeff_df.to_csv(s10_dir / "S10ab_observed_vs_fitted_complex_coefficients_all_images.csv", index=False, encoding="utf-8-sig")
        # Representative subset by beta quantiles for plotting observed/fitted complex points.
        beta = pd.to_numeric(fit_df["beta_iso"], errors="coerce")
        reps = []
        for label, q in [("low_w", 0.10), ("median_w", 0.50), ("high_w", 0.90)]:
            val = beta.quantile(q)
            idx = (beta - val).abs().idxmin()
            reps.append({"representative_type": label, "name": fit_df.loc[idx, "name"], "array_index": fit_df.loc[idx, "array_index"], "beta_iso": fit_df.loc[idx, "beta_iso"]})
        reps_df = pd.DataFrame(reps)
        reps_df.to_csv(s10_dir / "S10ab_representative_complex_fit_selection.csv", index=False, encoding="utf-8-sig")
        rep_coeff = coeff_df.merge(reps_df[["name", "representative_type"]], on="name", how="inner")
        rep_coeff.to_csv(s10_dir / "S10ab_representative_observed_fitted_complex_coefficients.csv", index=False, encoding="utf-8-sig")

    # Isotropic vs anisotropic width comparison for Fig. S10c
    cols = [c for c in ["name", "short_name", "beta_iso", "anisotropic_width_beta_equiv", "anisotropic_magnitude_eta", "anisotropic_orientation_deg", "isotropic_residual_fraction", "anisotropic_residual_fraction"] if c in fit_df.columns]
    fit_df[cols].to_csv(s10_dir / "S10c_isotropic_vs_anisotropic_width_scatter.csv", index=False, encoding="utf-8-sig")

    # Capped-vs-continuous distribution for Fig. S10d
    dist_df = fit_df.copy()
    dist_df["cap_status"] = np.where(dist_df["beta_grid_railed_high"].astype(bool), "capped_at_upper_bound", "continuous_fit")
    dist_cols = [c for c in ["name", "short_name", "beta_iso", "cap_status", "fit_included_continuous", "c_beta_signed_norm", "abs_c_beta_norm", "theta_beta_over_AH_deg_norm", "raw_current_floor_log10_abs_p05"] if c in dist_df.columns]
    dist_df[dist_cols].to_csv(s10_dir / "S10d_width_distribution_capped_vs_continuous.csv", index=False, encoding="utf-8-sig")

    # Anisotropy distribution/floor sorting for Fig. S10f
    aniso_cols = [c for c in ["name", "short_name", "anisotropic_magnitude_eta", "anisotropic_orientation_deg", "anisotropic_width_beta_equiv", "raw_current_floor_log10_abs_p05", "beta_iso", "fit_included_continuous"] if c in fit_df.columns]
    fit_df[aniso_cols].to_csv(s10_dir / "S10f_anisotropy_vs_current_floor.csv", index=False, encoding="utf-8-sig")

    # Table S3 summary statistics and correlations.
    rows = []
    def add_summary(metric: str, subset_label: str, mask):
        if metric not in fit_df.columns:
            return
        vals = pd.to_numeric(fit_df.loc[mask, metric], errors="coerce").dropna()
        rows.append({
            "subset": subset_label,
            "metric": metric,
            "n": int(vals.size),
            "median": float(vals.median()) if vals.size else np.nan,
            "p25": float(vals.quantile(0.25)) if vals.size else np.nan,
            "p75": float(vals.quantile(0.75)) if vals.size else np.nan,
            "min": float(vals.min()) if vals.size else np.nan,
            "max": float(vals.max()) if vals.size else np.nan,
            "mean": float(vals.mean()) if vals.size else np.nan,
            "std": float(vals.std(ddof=1)) if vals.size > 1 else np.nan,
        })
    masks = {
        "all_fits_including_capped": np.ones(len(fit_df), dtype=bool),
        "continuous_cap_excluded": fit_df["fit_included_continuous"].astype(bool).to_numpy() if "fit_included_continuous" in fit_df.columns else np.ones(len(fit_df), dtype=bool),
    }
    for subset, mask in masks.items():
        for metric in ["beta_iso", "anisotropic_width_beta_equiv", "anisotropic_magnitude_eta", "isotropic_residual_fraction", "anisotropic_residual_fraction"]:
            add_summary(metric, subset, mask)
    summary_df = pd.DataFrame(rows)
    summary_df.to_csv(s10_dir / "Table_S3_readout_fit_summary_statistics.csv", index=False, encoding="utf-8-sig")

    floor_col = find_floor_col(fit_df)
    corr_rows = []
    variables = {"floor_log10": floor_col, "c_B_signed": "c_beta_signed_norm", "abs_c_B": "abs_c_beta_norm", "theta_deg": "theta_beta_over_AH_deg_norm"}
    descriptors = ["beta_iso", "anisotropic_width_beta_equiv", "anisotropic_magnitude_eta", "anisotropic_orientation_deg", "isotropic_residual_fraction", "anisotropic_residual_fraction"]
    for subset, mask in masks.items():
        sub = fit_df.loc[mask].copy()
        for desc in descriptors:
            if desc not in sub.columns:
                continue
            for var_label, var_col in variables.items():
                if var_col is None or var_col not in sub.columns:
                    continue
                rho, pval, lo, hi, n = bootstrap_spearman_ci(sub[desc], sub[var_col], seed=BOOTSTRAP_SEED + len(corr_rows))
                corr_rows.append({
                    "subset": subset,
                    "descriptor": desc,
                    "variable": var_label,
                    "variable_column": var_col,
                    "spearman_rho": rho,
                    "spearman_p": pval,
                    "rho_ci95_low": lo,
                    "rho_ci95_high": hi,
                    "n": n,
                })
    corr_df = pd.DataFrame(corr_rows)
    corr_df.to_csv(s10_dir / "Table_S3_readout_fit_correlation_summary.csv", index=False, encoding="utf-8-sig")

    # Robustness specs for Fig. S10e: correlations under fit/subset variants.
    robust_rows = []
    floor_col = floor_col or "raw_current_floor_log10_abs_p05"
    for snr_thr in ROBUSTNESS_SNR_THRESHOLDS:
        mask = np.ones(len(fit_df), dtype=bool)
        if "sqrt3_amp_snr" in fit_df.columns:
            mask &= pd.to_numeric(fit_df["sqrt3_amp_snr"], errors="coerce").fillna(-np.inf).to_numpy() >= snr_thr
        for include_capped in [False, True]:
            mask2 = mask.copy()
            if not include_capped and "fit_included_continuous" in fit_df.columns:
                mask2 &= fit_df["fit_included_continuous"].astype(bool).to_numpy()
            sub = fit_df.loc[mask2]
            for desc in ["beta_iso", "beta_shellratio_structure_corrected", "anisotropic_width_beta_equiv", "anisotropic_magnitude_eta"]:
                if desc not in sub.columns:
                    continue
                for var in [floor_col, "c_beta_signed_norm", "abs_c_beta_norm", "theta_beta_over_AH_deg_norm"]:
                    if var is None or var not in sub.columns:
                        continue
                    rho, pval, lo, hi, n = bootstrap_spearman_ci(sub[desc], sub[var], seed=BOOTSTRAP_SEED + len(robust_rows))
                    robust_rows.append({
                        "specification": f"snr_ge_{snr_thr:g}_{'including_capped' if include_capped else 'cap_excluded'}",
                        "descriptor": desc,
                        "variable": var,
                        "spearman_rho": rho,
                        "rho_ci95_low": lo,
                        "rho_ci95_high": hi,
                        "spearman_p": pval,
                        "n": n,
                    })
    pd.DataFrame(robust_rows).to_csv(s10_dir / "S10e_robustness_correlation_specs.csv", index=False, encoding="utf-8-sig")

    # Compact fit-count summary.
    counts = pd.DataFrame([{
        "N_fit": int(len(fit_df)),
        "N_capped_upper_bound": int(fit_df["beta_grid_railed_high"].astype(bool).sum()) if "beta_grid_railed_high" in fit_df.columns else 0,
        "N_continuous_cap_excluded": int(fit_df["fit_included_continuous"].astype(bool).sum()) if "fit_included_continuous" in fit_df.columns else int(len(fit_df)),
        "BETA_MAX": float(BETA_MAX),
        "BETA_MIN": float(BETA_MIN),
    }])
    counts.to_csv(s10_dir / "Table_S3_fit_counts.csv", index=False, encoding="utf-8-sig")


def residualize_to_mean_readout(y: np.ndarray, Z: np.ndarray) -> np.ndarray:
    """Return y evaluated at ensemble-mean Z by removing the centered Z contribution."""
    y = np.asarray(y, dtype=float)
    Z = np.asarray(Z, dtype=float)
    if Z.ndim == 1:
        Z = Z[:, None]
    m = np.isfinite(y) & np.isfinite(Z).all(axis=1)
    out = np.full_like(y, np.nan, dtype=float)
    if m.sum() < max(4, Z.shape[1] + 2):
        return out
    yy = y[m]
    ZZ = Z[m]
    Zmean = np.nanmean(ZZ, axis=0, keepdims=True)
    X = np.column_stack([np.ones(ZZ.shape[0]), ZZ - Zmean])
    coef, *_ = np.linalg.lstsq(X, yy, rcond=None)
    # y_at_mean_readout = y - beta_z @ (Z - meanZ)
    out[m] = yy - (ZZ - Zmean) @ coef[1:]
    return out


def compute_Table_S4(fit_df: pd.DataFrame, out_dir: Path) -> None:
    s4_dir = ensure_dir(out_dir / "Table_S4_readout_correction")
    if fit_df.empty:
        return
    floor_col = find_floor_col(fit_df)
    if floor_col is None:
        warnings.warn("No current-floor column found; skipping Table S4.")
        return
    mask = fit_df["fit_included_continuous"].astype(bool).to_numpy() if "fit_included_continuous" in fit_df.columns else np.ones(len(fit_df), dtype=bool)
    df = fit_df.loc[mask].copy()
    rows = []
    corrected_df = df[["name"]].copy()
    for label, col in CONTRAST_COLUMNS.items():
        if col not in df.columns:
            continue
        y = pd.to_numeric(df[col], errors="coerce").to_numpy(dtype=float)
        ell = pd.to_numeric(df[floor_col], errors="coerce").to_numpy(dtype=float)
        z_iso = pd.to_numeric(df["beta_iso"], errors="coerce").to_numpy(dtype=float) if "beta_iso" in df.columns else np.full(len(df), np.nan)
        z_full_cols = []
        if "anisotropic_magnitude_eta" in df.columns and "anisotropic_orientation_deg" in df.columns:
            eta = pd.to_numeric(df["anisotropic_magnitude_eta"], errors="coerce").to_numpy(dtype=float)
            phi = np.deg2rad(pd.to_numeric(df["anisotropic_orientation_deg"], errors="coerce").to_numpy(dtype=float))
            z_full_cols = [z_iso, eta * np.cos(2 * phi), eta * np.sin(2 * phi)]
        else:
            z_full_cols = [z_iso]
        y_iso = residualize_to_mean_readout(y, z_iso)
        y_full = residualize_to_mean_readout(y, np.column_stack(z_full_cols))
        corrected_df[f"{label}_uncorrected"] = y
        corrected_df[f"{label}_iso_corrected"] = y_iso
        corrected_df[f"{label}_full_corrected"] = y_full
        for correction, yy in [("uncorrected", y), ("isotropic_w", y_iso), ("full_w_eta_phi", y_full)]:
            rho, pval, lo, hi, n = bootstrap_spearman_ci(ell, yy, seed=BOOTSTRAP_SEED + len(rows))
            rows.append({
                "coordinate_label": label,
                "coordinate_column": col,
                "floor_column": floor_col,
                "correction": correction,
                "spearman_rho_vs_floor": rho,
                "spearman_p": pval,
                "rho_ci95_low": lo,
                "rho_ci95_high": hi,
                "n": n,
            })
    table = pd.DataFrame(rows)
    # fractional reduction in |rho| relative to uncorrected for each coordinate
    if not table.empty:
        out_rows = []
        for coord, g in table.groupby("coordinate_label"):
            base = g.loc[g["correction"] == "uncorrected", "spearman_rho_vs_floor"]
            base_rho = float(base.iloc[0]) if not base.empty else np.nan
            for _, r in g.iterrows():
                rr = r.to_dict()
                rr["abs_rho"] = abs(rr["spearman_rho_vs_floor"]) if np.isfinite(rr["spearman_rho_vs_floor"]) else np.nan
                rr["fractional_reduction_in_abs_rho_vs_uncorrected"] = ((abs(base_rho) - abs(rr["spearman_rho_vs_floor"])) / abs(base_rho)) if np.isfinite(base_rho) and abs(base_rho) > 0 and np.isfinite(rr["spearman_rho_vs_floor"]) else np.nan
                out_rows.append(rr)
        table = pd.DataFrame(out_rows)
    table.to_csv(s4_dir / "Table_S4_contrast_floor_correlations_before_after_readout_correction.csv", index=False, encoding="utf-8-sig")
    corrected_df.to_csv(s4_dir / "Table_S4_corrected_coordinates_per_image.csv", index=False, encoding="utf-8-sig")


def compute_Table_S5(fit_df: pd.DataFrame, out_dir: Path) -> None:
    s5_dir = ensure_dir(out_dir / "Table_S5_component_regressions")
    if fit_df.empty:
        return
    floor_col = find_floor_col(fit_df)
    if floor_col is None or "beta_iso" not in fit_df.columns:
        warnings.warn("Missing floor or beta_iso column; skipping Table S5.")
        return
    mask = fit_df["fit_included_continuous"].astype(bool).to_numpy() if "fit_included_continuous" in fit_df.columns else np.ones(len(fit_df), dtype=bool)
    df = fit_df.loc[mask].copy()
    df["w_centered"] = pd.to_numeric(df["beta_iso"], errors="coerce") - pd.to_numeric(df["beta_iso"], errors="coerce").mean()
    df["ell_centered"] = pd.to_numeric(df[floor_col], errors="coerce") - pd.to_numeric(df[floor_col], errors="coerce").mean()
    rows = []
    driver_specs = [("readout_width_w", "w_centered", "beta_iso"), ("current_floor_ell", "ell_centered", floor_col)]
    response_specs = [("c_AH", "c_AH_norm"), ("abs_c_B", "abs_c_beta_norm"), ("c_B_signed", "c_beta_signed_norm")]
    for driver_label, driver_centered_col, driver_raw_col in driver_specs:
        if driver_centered_col not in df.columns:
            continue
        x = pd.to_numeric(df[driver_centered_col], errors="coerce")
        for response_label, ycol in response_specs:
            if ycol not in df.columns:
                continue
            y = pd.to_numeric(df[ycol], errors="coerce")
            reg = linear_regression_centered(x, y)
            ci = bootstrap_linear_regression_ci(x, y, seed=BOOTSTRAP_SEED + len(rows))
            rows.append({
                "driver": driver_label,
                "driver_centered_column": driver_centered_col,
                "driver_raw_column": driver_raw_col,
                "driver_mean_raw": float(pd.to_numeric(df[driver_raw_col], errors="coerce").mean()),
                "response": response_label,
                "response_column": ycol,
                **reg,
                **ci,
            })
    reg_df = pd.DataFrame(rows)
    reg_df.to_csv(s5_dir / "Table_S5_component_level_univariate_regressions.csv", index=False, encoding="utf-8-sig")

    # Partial regressions controlling for the other driver.
    partial_rows = []
    for response_label, ycol in response_specs:
        if ycol not in df.columns:
            continue
        y = pd.to_numeric(df[ycol], errors="coerce").to_numpy(dtype=float)
        Xraw = np.column_stack([
            pd.to_numeric(df["w_centered"], errors="coerce").to_numpy(dtype=float),
            pd.to_numeric(df["ell_centered"], errors="coerce").to_numpy(dtype=float),
        ])
        m = np.isfinite(y) & np.isfinite(Xraw).all(axis=1)
        if m.sum() < 5:
            continue
        X = np.column_stack([np.ones(m.sum()), Xraw[m]])
        coef, *_ = np.linalg.lstsq(X, y[m], rcond=None)
        yhat = X @ coef
        ss_res = float(np.sum((y[m]-yhat)**2))
        ss_tot = float(np.sum((y[m]-np.mean(y[m]))**2))
        partial_rows.append({
            "response": response_label,
            "response_column": ycol,
            "n": int(m.sum()),
            "intercept": float(coef[0]),
            "partial_slope_w_controlling_ell": float(coef[1]),
            "partial_slope_ell_controlling_w": float(coef[2]),
            "r2_two_driver_model": 1.0 - ss_res/ss_tot if ss_tot > 0 else np.nan,
        })
    pd.DataFrame(partial_rows).to_csv(s5_dir / "Table_S5_component_level_partial_regressions.csv", index=False, encoding="utf-8-sig")

    # Signature angle in c_AH - |c_B| plane using standardized displacements.
    sig_rows = []
    for driver_label in ["readout_width_w", "current_floor_ell"]:
        sub = reg_df[reg_df["driver"] == driver_label]
        cah = sub.loc[sub["response"] == "c_AH", "standardized_displacement"]
        cb = sub.loc[sub["response"] == "abs_c_B", "standardized_displacement"]
        if not cah.empty and not cb.empty:
            x = float(cah.iloc[0])
            y = float(cb.iloc[0])
            angle = math.degrees(math.atan2(y, x))
            sig_rows.append({"driver": driver_label, "delta_c_AH_per_1sd_driver": x, "delta_abs_c_B_per_1sd_driver": y, "signature_angle_deg": angle, "signature_magnitude": math.sqrt(x*x+y*y)})
    sig_df = pd.DataFrame(sig_rows)
    if len(sig_df) >= 2:
        v0 = sig_df.loc[sig_df["driver"] == "readout_width_w", ["delta_c_AH_per_1sd_driver", "delta_abs_c_B_per_1sd_driver"]].to_numpy(dtype=float)
        v1 = sig_df.loc[sig_df["driver"] == "current_floor_ell", ["delta_c_AH_per_1sd_driver", "delta_abs_c_B_per_1sd_driver"]].to_numpy(dtype=float)
        if v0.size == 2 and v1.size == 2:
            a = v0[0]
            b = v1[0]
            denom = np.linalg.norm(a) * np.linalg.norm(b)
            sep = math.degrees(math.acos(np.clip(float(np.dot(a,b)/denom), -1, 1))) if denom > 0 else np.nan
            sig_df["signature_angle_separation_deg_readout_vs_floor"] = sep
    sig_df.to_csv(s5_dir / "Table_S5_signature_vectors_and_angle_separation.csv", index=False, encoding="utf-8-sig")
    df[["name", "w_centered", "ell_centered", floor_col, "beta_iso"] + [c for _, c in response_specs if c in df.columns]].to_csv(
        s5_dir / "Table_S5_regression_source_data_per_image.csv", index=False, encoding="utf-8-sig"
    )

# =============================================================================
# Workbook/index
# =============================================================================

def write_master_index(out_dir: Path) -> None:
    rows = []
    for p in sorted(out_dir.rglob("*.csv")):
        rel = p.relative_to(out_dir).as_posix()
        rows.append({"relative_path": rel, "file_name": p.name, "folder": p.parent.relative_to(out_dir).as_posix() if p.parent != out_dir else "."})
    idx = pd.DataFrame(rows)
    idx.to_csv(out_dir / "SI_source_data_index.csv", index=False, encoding="utf-8-sig")
    readme = [
        "# Source data for SI Fig. S8-S10 and Tables S2-S5",
        "",
        "This folder contains CSV files calculated from motif_analysis_arrays.npz and the main motif-coordinate tables.",
        "",
        "## Fig. S8",
        "- Fig_S8_peak_detectability/S8a_shell_marker_points_for_overlay.csv",
        "- Fig_S8_peak_detectability/S8b_ensemble_mean_shell_power_summary.csv",
        "- Fig_S8_peak_detectability/S8c_per_image_sqrt3_peak_snr.csv",
        "- Fig_S8_peak_detectability/S8d_fft_map_*_xyz.csv",
        "",
        "## Fig. S9 / Table S2",
        "- Fig_S9_synthetic_validation/S9b_synthetic_width_sensitivity_sweep.csv",
        "- Fig_S9_synthetic_validation/S9c_synthetic_contrast_specificity_sweep.csv",
        "- Fig_S9_synthetic_validation/S9d_synthetic_anisotropy_validation.csv",
        "- Fig_S9_synthetic_validation/S9e_two_axis_validation_summary_for_plot.csv",
        "- Fig_S9_synthetic_validation/Table_S2_synthetic_validation_metrics.csv",
        "",
        "## Fig. S10 / Table S3",
        "- Fig_S10_readout_fit_robustness/S10ab_representative_observed_fitted_complex_coefficients.csv",
        "- Fig_S10_readout_fit_robustness/S10c_isotropic_vs_anisotropic_width_scatter.csv",
        "- Fig_S10_readout_fit_robustness/S10d_width_distribution_capped_vs_continuous.csv",
        "- Fig_S10_readout_fit_robustness/S10e_robustness_correlation_specs.csv",
        "- Fig_S10_readout_fit_robustness/S10f_anisotropy_vs_current_floor.csv",
        "- Fig_S10_readout_fit_robustness/Table_S3_readout_fit_summary_statistics.csv",
        "- Fig_S10_readout_fit_robustness/Table_S3_readout_fit_correlation_summary.csv",
        "- Fig_S10_readout_fit_robustness/Table_S3_fit_counts.csv",
        "",
        "## Table S4",
        "- Table_S4_readout_correction/Table_S4_contrast_floor_correlations_before_after_readout_correction.csv",
        "- Table_S4_readout_correction/Table_S4_corrected_coordinates_per_image.csv",
        "",
        "## Table S5",
        "- Table_S5_component_regressions/Table_S5_component_level_univariate_regressions.csv",
        "- Table_S5_component_regressions/Table_S5_component_level_partial_regressions.csv",
        "- Table_S5_component_regressions/Table_S5_signature_vectors_and_angle_separation.csv",
        "- Table_S5_component_regressions/Table_S5_regression_source_data_per_image.csv",
        "",
        "Notes:",
        "- FFT shell coefficients use the 120-degree direct-cell reciprocal metric q2=h^2+h*k+k^2.",
        "- The primary readout-width coordinate is beta_iso from the joint complex coefficient fit using first and sqrt(3) shells.",
        "- Table S4 readout corrections are linear evaluations at the ensemble-mean readout descriptor.",
    ]
    (out_dir / "README_SI_source_data.md").write_text("\n".join(readme), encoding="utf-8")


def compile_excel_workbook(out_dir: Path) -> None:
    xlsx_path = out_dir / "SI_S8_S10_TableS2_S5_source_data.xlsx"
    csvs = sorted([p for p in out_dir.rglob("*.csv") if p.name != "SI_source_data_index.csv"])
    with pd.ExcelWriter(xlsx_path, engine="openpyxl") as writer:
        pd.read_csv(out_dir / "SI_source_data_index.csv").to_excel(writer, sheet_name="index", index=False)
        used = {"index"}
        for p in csvs:
            try:
                df = pd.read_csv(p)
            except Exception:
                continue
            # Excel row limit guard.
            if len(df) > 1_000_000:
                continue
            stem = p.stem
            # Prefix with folder initials to avoid duplicate sheet names.
            folder = p.parent.name
            sheet = f"{folder[:6]}_{stem[:22]}"[:31]
            base = sheet
            j = 1
            while sheet in used:
                suffix = f"_{j}"
                sheet = (base[:31-len(suffix)] + suffix)[:31]
                j += 1
            used.add(sheet)
            df.to_excel(writer, sheet_name=sheet, index=False)

# =============================================================================
# Main
# =============================================================================

def main() -> None:
    parser = argparse.ArgumentParser(description="Compute source data for SI Fig. S8-S10 and Tables S2-S5.")
    parser.add_argument("--analysis-dir", "--analysis_dir", dest="analysis_dir", required=True, help="Primary-analysis output directory")
    parser.add_argument("--out-dir", "--out_dir", dest="out_dir", default=None, help="Output directory; defaults to ANALYSIS_DIR/supplementary_source_data")
    parser.add_argument("--map-key", "--map_key", dest="map_key", default=MAP_KEY, help="Array key in motif_analysis_arrays.npz")
    parser.add_argument("--skip-excel", "--skip_excel", dest="skip_excel", action="store_true", help="Do not compile the Excel workbook")
    args = parser.parse_args()

    analysis_dir = Path(args.analysis_dir).expanduser().resolve()
    out_dir = ensure_dir(Path(args.out_dir).expanduser().resolve() if args.out_dir else analysis_dir / OUTPUT_FOLDER_NAME)
    npz_path = analysis_dir / "motif_analysis_arrays.npz"

    print(f"Loading maps from {npz_path} [{args.map_key}] ...")
    maps, names, arrays = load_npz_maps(npz_path, args.map_key)
    coord_df = load_coord_table(analysis_dir, names)
    positions_by_name = load_site_positions(analysis_dir, coord_df, names)

    # Keep map/name order aligned with coord table if possible.
    print(f"Computing Fig. S8 shell detectability for {len(names)} maps ...")
    s8_snr_df = compute_S8(maps, names, out_dir)

    print("Computing real-data readout form-factor fits ...")
    fit_df, coeff_df = compute_real_readout_fits(maps, names, coord_df, positions_by_name, s8_snr_df, out_dir)
    fit_df = add_floor_and_coord_columns(fit_df, coord_df)
    # Update the saved real-fit file after merging metadata.
    fit_save_dir = ensure_dir(out_dir / "readout_form_factor_fits")
    if not fit_df.empty:
        fit_df.to_csv(fit_save_dir / "readout_fit_per_image.csv", index=False, encoding="utf-8-sig")

    print("Computing synthetic validation for Fig. S9 / Table S2 ...")
    compute_synthetic_validation(positions_by_name, out_dir)

    print("Writing Fig. S10 / Table S3 source data ...")
    compute_table_S3_and_S10(fit_df, coeff_df, out_dir)

    print("Writing Table S4 readout-correction correlations ...")
    compute_Table_S4(fit_df, out_dir)

    print("Writing Table S5 component regressions ...")
    compute_Table_S5(fit_df, out_dir)

    print("Writing index and workbook ...")
    write_master_index(out_dir)
    if not args.skip_excel:
        compile_excel_workbook(out_dir)

    print("\nDONE")
    print(f"Output folder: {out_dir}")
    print(f"Index: {out_dir / 'SI_source_data_index.csv'}")
    print(f"README: {out_dir / 'README_SI_source_data.md'}")

if __name__ == "__main__":
    main()
